[versions]
kotlin = "2.2.0"
minecraft = "1.21.8"
fabric-loom = "1.11.4"
fabric-loader = "0.16.14"
fabric-api = "0.129.0+1.21.8"
fabric-kotlin = "1.13.4+kotlin.2.2.0"
fabric-permissions = "0.4.0"
serverevents = "2025.7.3"

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-permissions = { group = "me.lucko", name = "fabric-permissions-api", version.ref = "fabric-permissions" }
serverevents = { group = "icu.suc", name = "serverevents", version.ref = "serverevents" }

[plugins]
maven = { id = "maven-publish" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }